spring:
  application:
    name: fluffytime
  datasource:
    url: jdbc:mysql://localhost:3306/fluffydb
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


aws:
  s3:
    bucket-name: fluffytime-bucket
    region: ${AWS_REGION}
  credentials:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
