spring:
  application:
    name: fluffytime

  datasource:
    url: jdbc:mysql://localhost:3307/fluffydb
    username: developer
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: 1234
      password: 1234

  ## GMail 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: andcl1227@gmail.com
    password: fcqt tawt uyju ozto
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
      timeout: 5000
