spring:
  application:
    name: fluffytime
  datasource:
    url: jdbc:mysql://localhost:3306/fluffydb
    username: developer
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: 1234
      password: 1234